robotis_mini:
  joint_list: [r_shoulder_joint, l_shoulder_joint, r_biceps_joint, l_biceps_joint, r_elbow_joint, l_elbow_joint, r_hip_joint, l_hip_joint, r_thigh_joint, l_thigh_joint, r_knee_joint, l_knee_joint, r_ankle_joint, l_ankle_joint, r_foot_joint, l_foot_joint]
